Iter9
vadim-ivlev/url-shortener pull request #10
Opened 2024-10-01 00:45 UTC by vadim-ivlev

2024-10-01 18:31 UTC, nburunova requested changes

2024-10-01 18:31 UTC, nburunova commented on internal/config/config.go
> +var Address string
тут лучше финальный набор настроек оформить в  структуру, а не хранить отдельными переменными. Так как настроек будет становится всё больше и иногда надо будет анализировать комбинацию настроек, в этом случае будет удобнее, если они все будут  в одной структуре передаваться

2024-10-01 18:31 UTC, nburunova commented on cmd/shortener/main.go
> +	filestorage "github.com/vadim-ivlev/url-shortener/internal/iter9-filestorage"
лучше в путях и именах пакетов не использовать отсылки к итерации, так как потом в других итерациях этот пакет может дорабатываться

2024-10-01 18:31 UTC, nburunova commented on internal/storage/storage.go
> +	dm = &DoubleMap{
что будет если два раза вызвать create? Возможно стоить обезопасить мапу от такого сценария

2024-10-01 18:31 UTC, nburunova commented on internal/storage/storage.go
> +	// fmt.Println("storage package initialized")
отладочный принт случайно залетел сюда

2024-10-01 18:31 UTC, nburunova commented on internal/handlers/handlers.go
> +			// http.Error(w, "Cannot save shortened url in the filestorage", http.StatusInternalServerError)
отладочные принты

2024-10-01 18:31 UTC, nburunova commented on internal/handlers/handlers.go
> +	body, err := io.ReadAll(r.Body)
не вызывать r.Body.Close(), 
// The Server will close the request body. The ServeHTTP
	// Handler does not need to. 
https://github.com/golang/go/blob/e470a00cdff2c4c13162dc8887fedd6812393514/src/net/http/request.go#L182

2024-10-01 18:31 UTC, nburunova commented on internal/handlers/handlers.go
> +		w.Write([]byte(`{"error":"Internal server error"}`))
тут можно текст ошибки отправить err.Error(), клиенту будет понятнее, что именно пошло не т ак

2024-10-01 18:31 UTC, nburunova commented on internal/handlers/handlers.go
> +	type apiShortenRequest struct {
обычно типы объявляем вне тела функции

2024-10-01 23:31 UTC, vadim-ivlev commented on internal/config/config.go
> +var Address string
Исправлено.

2024-10-01 23:38 UTC, vadim-ivlev commented on internal/storage/storage.go
> +	dm = &DoubleMap{
Исправлено.

2024-10-01 23:39 UTC, vadim-ivlev commented on internal/storage/storage.go
> +	// fmt.Println("storage package initialized")
Исправлено

2024-10-01 23:40 UTC, vadim-ivlev commented on internal/handlers/handlers.go
> +			// http.Error(w, "Cannot save shortened url in the filestorage", http.StatusInternalServerError)
Исправлено

2024-10-01 23:47 UTC, vadim-ivlev commented on internal/handlers/handlers.go
> +	body, err := io.ReadAll(r.Body)
Исправлено

2024-10-01 23:48 UTC, vadim-ivlev commented on internal/handlers/handlers.go
> +		w.Write([]byte(`{"error":"Internal server error"}`))
Исправлено

2024-10-01 23:51 UTC, vadim-ivlev commented on internal/handlers/handlers.go
> +	type apiShortenRequest struct {
Исправлено

2024-10-01 23:59 UTC, vadim-ivlev commented on cmd/shortener/main.go
> +	filestorage "github.com/vadim-ivlev/url-shortener/internal/iter9-filestorage"
Исправлено

2024-10-02 00:14 UTC, vadim-ivlev commented
Надежда, код исправлен и запушен.
Спасибо за замечания и быстрый ревью.

2024-10-02 00:26 UTC, vadim-ivlev commented
Надежда, код исправлен и запушен.
Спасибо за замечания и быструю проверку.

2024-10-03 09:17 UTC, nburunova commented on internal/handlers/handlers.go
> +	type apiShortenRequest struct {
это не исправлено

2024-10-03 13:48 UTC, vadim-ivlev commented on internal/handlers/handlers.go
> +	type apiShortenRequest struct {
Сорри )). Пропустил . Определение типа apiShortenRequest  изначально было помещено внутрь функции, потому, что нигде за пределами этой функции этот тип не использовался. 
Теперь избавился от определения этого типа вовсе.
Новый код запушен, 
Спасибо.

2024-10-04 05:55 UTC, vadim-ivlev commented on internal/handlers/handlers.go
> +	type apiShortenRequest struct {
Не понимаю, что происходит. Ошибки давно исправлены.

2024-10-04 06:12 UTC, nburunova approved these changes

2024-10-04 06:12 UTC, nburunova commented on internal/handlers/handlers.go
> +	var req struct {
объявление структур вынеси вне тела функции, обычно типы объявляются вне функций

2024-10-04 06:12 UTC, nburunova commented on internal/handlers/handlers.go
> +	type apiShortenResponse struct {
объявление структур вынеси вне тела функции, обычно типы объявляются вне функций

2024-10-04 08:46 UTC, merged