Iter13
vadim-ivlev/url-shortener pull request #16
Opened 2024-10-07 20:26 UTC by vadim-ivlev

Should have 31 commits instead of 81

2024-10-09 13:10 UTC, nburunova requested changes

2024-10-09 13:10 UTC, nburunova commented on internal/app/app.go
> +	db.Connect(1)
неговорящий аргумент, когда читаешь код, не понятно, что значит 1?

2024-10-09 13:10 UTC, nburunova commented on internal/db/db_dataload.go
> +			log.Warn().Err(err).Msg("GetData Cannot scan row")
если мы не смогли считать запись 1, однако считали запись 2, то err будет равно nil, однако в data будет не хватать одной записи, корректное ли это поведение?

2024-10-09 13:10 UTC, nburunova commented on internal/db/db_dataload.go
> +	return data, err
тут неопределенность: err == nil, еслт последнюю запись считали без ошибок, и err != nil если последнюю запись считали с ошибкой. При этом результаты считывания предыдущих записей не учитываются, так как err перетирается.
Тут нужно или явно вернуть nil или явно вернуть какую-то ошибку

2024-10-09 13:10 UTC, nburunova commented on internal/app/app.go
> +func AddToStore(shortID, originalURL string) {
возможно стоит возвращать ошибку, если не удалось сохранить данные в хранилище. Иначе мы будем терять данные и не узнаем об этом и попытаемся сделать retry или вернуть пользователю ошибку в ответе. То есть пользователь будет пытаться что-то сохранять и ождать, что всё ок. А на самом деле у нас в БД\файл не сохранилось или вообще в параметрах не установлены.

2024-10-09 13:10 UTC, nburunova commented on internal/db/db_dataload.go
> +func LoadData() {
название немного смущает, кажется, что эта функция загружает данные в БД. Может назвать как-то явно? Например DumpDataToStorage?

 Еще фукнция не возвращает ошибку, это нормально, если мы вызываем LoadData, происходит ошибка, но вызывающий код не узнает об ошибке?

2024-10-09 13:10 UTC, nburunova commented on internal/handlers/handlers.go
> +		app.AddToStore(savedID, originalURL)
если не удалось сохранить в БД, надо ли возвращать ошибку пользователю или можно не сохранять?

2024-10-09 13:10 UTC, nburunova commented on internal/handlers/handlers.go
> +// added -  флаг, добавлен ли новый короткий URL в БД или файловое хранилище.
added будет равен true, если url был добавлен в хранилище в памяти , но не выл добавлен в БД\файл

2024-10-09 13:10 UTC, nburunova commented on internal/handlers/handlers.go
> +		w.WriteHeader(http.StatusInternalServerError)
вот тут можно было бы возвращать ошибку из  IsConnected и потом выдавать текст ошибки пользователю в w, было бы информативнее

2024-10-09 13:10 UTC, nburunova commented on internal/handlers/handlers.go
> +func generateAndSaveShortURL(originalURL string) (shortURL string, added bool) {
а должны ли мы в хендлере и сохранять в  storage и в БД/файл? пусть всё делает storage. Я к тому, что хендлеру не обязательно знать, что у нас есть storage в памяти и БД\файл. Может скроем сохранение в одном объекте.
А зачем там отдельно и storage в памяти и в БД\файле? Там же данные дублируются по сути? Можем оставить что-то одно? или хранение в памяти или в БД\файле?

2024-10-14 17:14 UTC, vadim-ivlev commented on internal/db/db_dataload.go
> +			log.Warn().Err(err).Msg("GetData Cannot scan row")
Мне показалось, что любое количество загруженных записей лучше чем ни одной. Пользователю не придется пересоздавать все записи, а только некоторые.

2024-10-14 17:18 UTC, vadim-ivlev commented on internal/app/app.go
> +	db.Connect(1)
Переименовал Connect(numAttempts int) в TryToConnect(numAttempts int). Название аргумента numAttempts по моему говорящее. Добавил в комментарий вызова функции, что это количество попыток.

2024-10-14 17:21 UTC, vadim-ivlev commented on internal/db/db_dataload.go
> +	return data, err
Согласен.  Явно вернул nil.

2024-10-14 21:45 UTC, vadim-ivlev commented on internal/app/app.go
> +func AddToStore(shortID, originalURL string) {
Добавил возврат ошибки при сохранении в постоянное хранилище. И во все функции вызывающие эту, включая хандлеры.

2024-10-15 18:19 UTC, vadim-ivlev commented on internal/db/db_dataload.go
> +func LoadData() {
Переименовал в LoadDataToStorage() (err error). И возвращает ошибку.

2024-10-15 18:25 UTC, vadim-ivlev commented on internal/handlers/handlers.go
> +		app.AddToStore(savedID, originalURL)
Теперь возвращаю пользователю ошибку если не удалось сохранить в постоянное хранилище.

2024-10-15 18:39 UTC, vadim-ivlev commented on internal/handlers/handlers.go
> +// added -  флаг, добавлен ли новый короткий URL в БД или файловое хранилище.
Сделал более тщательное описание возвращаемых значений. Переименовал added в aNewOne.
```go
// aNewOne -  флаг, новый ли это короткий URL. Если true, то это новый короткий URL.
// err - ошибка.
```

2024-10-15 18:56 UTC, vadim-ivlev commented on internal/handlers/handlers.go
> +		w.WriteHeader(http.StatusInternalServerError)
Теперь выдаю пользователю сообщение "No connection do database".

2024-10-15 21:58 UTC, vadim-ivlev commented on internal/handlers/handlers.go
> +func generateAndSaveShortURL(originalURL string) (shortURL string, added bool) {
В задаании сказано, что данные должны храниться в  оперативной памяти. 
- Потом добавилось требование сохранять дамп данных в файле и восстанавливать их из него. 
- Затем появилость требование сохранять данные в БД и восстанавливать состояние из из БД. 
- Затем появилость требование пользоваться или файловым хранилищем или БД или ни тем ни другим в зависимости от переменных окружения.

Таким образом нам нужны 3 независимых хранилища данных. 
- storage - хранилище в оперативной памяти.
- filestorage - файловое хранилище, 
- db - База Данных  

Причем хранилище в Оперативной памяти (storage) считаетсф первичным, поскольку должно работать при отключенных файловом хранилище и отключенном БД.

Поэтому мне показалась разумной конструкция при которой разные хранилища ничего не знают друг о друге и работают независимо друг от друга. Так мы обеспечиваем низкую связанность кода (low cohesion). 

Хандлеры реализуют слой бизнес логики, согласуя и объединяя работу  трех независимых хранилищ данных.

Для бизнес логики можно было бы создать отдельный модуль, но это только бы увеличило размер кода не давая других явных преимуществ.

Поскольку storage создавался, когда не было ещё файлового хранилища и базы данных я решил сохранить это в этом виде сохраняя независимость модулей и поместив связывающую бизнес логику в хандлеры.

По хорошему методы загрузки данных из перманентных хранилищьнужно бы перенес

2024-10-16 20:04 UTC, nburunova requested changes

2024-10-16 20:04 UTC, nburunova commented on internal/config/config.go
> +func getDefaultDatabaseDSN() string {
это точно нужно? в 9 тесте подразумевается работа на file storage, dsn может быть пустым, эта ситуация должна корректно обрабатываться

2024-10-16 20:04 UTC, nburunova commented on internal/db/db_dataload.go
> +func GetData() (data map[string]string, err error) {
запросы к БД советую делать с ctx, его нужно получать первым аргументом методах-запросах к БД.
В хендлерах ctx можно получать из request.Context() https://pkg.go.dev/net/http#Request.Context .
А в main можно создать context.Background()

Пример запросов к БД с конекстом  
![image](https://github.com/user-attachments/assets/0c72c372-74b7-4db3-b4f4-2c69d197096e)

2024-10-17 14:40 UTC, vadim-ivlev commented on internal/config/config.go
> +func getDefaultDatabaseDSN() string {
Удалил getDefaultDatabaseDSN() . Функция использовалась для прохождения локальных тестов.

2024-10-17 20:45 UTC, vadim-ivlev commented on internal/db/db_dataload.go
> +func GetData() (data map[string]string, err error) {
Добавил ctx во все запросы к базе данных.

Для уменьшения взаимозависимости модулей переметил функции загрузки данных 
из БД и файлового хранилища в пакет app.

2024-10-18 15:19 UTC, nburunova approved these changes

2024-10-21 07:57 UTC, merged